### ISSUE TITLE
iglineargauge - broken formatting and URLs

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#336]
Go here:
https://staging.igniteui.local/help/16.2/iglineargauge-overview

The formatting is wrong and the URL is broken in the screenshot:

![image](https://user-images.githubusercontent.com/9548226/28307697-634d9608-6bac-11e7-9095-61e94871dd8b.png)

**Comment by damyanpetev** [comment]
This is actually the same issue as #339 where list items get expanded by a in-page navigation anchor. That pushes the bullet up and also covers links so you can't click on them. 
We use an invisible element as high as the fixed header to allow the the page to navigate correctly to #hash links, but that seems to break lists in WebKit (not reproducible in FF). This will actually be fixed with an application update.
